server:
  port: 8190
  servlet:
    context-path: /web-market-cart

utils:
  cart:
    prefix: SPRING_WEB_APP_

spring:
  redis:
    host: localhost
    port: 6379

integrations:
  core-service:
    url: http://localhost:5555/core
    connect: 2000
    read: 10000
    write: 2000